// <auto-generated/>
#pragma warning disable CS0618
using Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.VersionNamespace.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.VersionNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \construction\autospecs\v1\projects\{projectId}\version
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VersionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Autodesk.ACC.construction.autospecs.v1.projects.item.version.item collection</summary>
        /// <param name="position">The AutoSpecs version ID of the project. For information about how to find the version ID, see the first few steps of the `Retrieve Submittal Log &lt;/en/docs/acc/v1/tutorials/autospecs/upload-document/&gt;`_ tutorial.</param>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.VersionNamespace.Item.WithVersionItemRequestBuilder"/></returns>
        public global::Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.VersionNamespace.Item.WithVersionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("versionId", position);
                return new global::Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.VersionNamespace.Item.WithVersionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.VersionNamespace.VersionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VersionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/construction/autospecs/v1/projects/{projectId}/version", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.VersionNamespace.VersionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VersionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/construction/autospecs/v1/projects/{projectId}/version", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
