// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Workflow
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WorkflowGetResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>A description of the workflow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>A list of project roles and their corresponding permitted assignees.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Workflow.WorkflowGetResponse_projectRolesMapping>? ProjectRolesMapping { get; set; }
#nullable restore
#else
        public List<global::Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Workflow.WorkflowGetResponse_projectRolesMapping> ProjectRolesMapping { get; set; }
#endif
        /// <summary>The region type of the workflow. Possible values: ``US``, ``EU``.</summary>
        public global::Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Workflow.WorkflowGetResponse_workflowType? WorkflowType { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Workflow.WorkflowGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Workflow.WorkflowGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Workflow.WorkflowGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "projectRolesMapping", n => { ProjectRolesMapping = n.GetCollectionOfObjectValues<global::Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Workflow.WorkflowGetResponse_projectRolesMapping>(global::Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Workflow.WorkflowGetResponse_projectRolesMapping.CreateFromDiscriminatorValue)?.AsList(); } },
                { "workflowType", n => { WorkflowType = n.GetEnumValue<global::Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Workflow.WorkflowGetResponse_workflowType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfObjectValues<global::Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Workflow.WorkflowGetResponse_projectRolesMapping>("projectRolesMapping", ProjectRolesMapping);
            writer.WriteEnumValue<global::Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Workflow.WorkflowGetResponse_workflowType>("workflowType", WorkflowType);
        }
    }
}
#pragma warning restore CS0618
