// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.Construction.Packages.V1.Projects.Item.Packages
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSortQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "asc")]
        #pragma warning disable CS1591
        Asc,
        #pragma warning restore CS1591
        [EnumMember(Value = "desc")]
        #pragma warning disable CS1591
        Desc,
        #pragma warning restore CS1591
        [EnumMember(Value = "sort=fieldName [desc]")]
        #pragma warning disable CS1591
        SortFieldNameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "createdAt")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "updatedAt")]
        #pragma warning disable CS1591
        UpdatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "displayId")]
        #pragma warning disable CS1591
        DisplayId,
        #pragma warning restore CS1591
        [EnumMember(Value = "sort=name")]
        #pragma warning disable CS1591
        SortName,
        #pragma warning restore CS1591
        [EnumMember(Value = "sort=createdAt desc")]
        #pragma warning disable CS1591
        SortCreatedAtDesc,
        #pragma warning restore CS1591
    }
}
