// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ImportPostResponse_failure_items : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The account_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountId { get; set; }
#nullable restore
#else
        public string AccountId { get; set; }
#endif
        /// <summary>The company_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyId { get; set; }
#nullable restore
#else
        public string CompanyId { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The errors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import.ImportPostResponse_failure_items_errors>? Errors { get; set; }
#nullable restore
#else
        public List<global::Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import.ImportPostResponse_failure_items_errors> Errors { get; set; }
#endif
        /// <summary>The industry_roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IndustryRoles { get; set; }
#nullable restore
#else
        public List<string> IndustryRoles { get; set; }
#endif
        /// <summary>The project_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>The services property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import.ImportPostResponse_failure_items_services? Services { get; set; }
#nullable restore
#else
        public global::Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import.ImportPostResponse_failure_items_services Services { get; set; }
#endif
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import.ImportPostResponse_failure_items"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import.ImportPostResponse_failure_items CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import.ImportPostResponse_failure_items();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_id", n => { AccountId = n.GetStringValue(); } },
                { "company_id", n => { CompanyId = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import.ImportPostResponse_failure_items_errors>(global::Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import.ImportPostResponse_failure_items_errors.CreateFromDiscriminatorValue)?.AsList(); } },
                { "industry_roles", n => { IndustryRoles = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "project_id", n => { ProjectId = n.GetStringValue(); } },
                { "services", n => { Services = n.GetObjectValue<global::Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import.ImportPostResponse_failure_items_services>(global::Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import.ImportPostResponse_failure_items_services.CreateFromDiscriminatorValue); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account_id", AccountId);
            writer.WriteStringValue("company_id", CompanyId);
            writer.WriteStringValue("email", Email);
            writer.WriteCollectionOfObjectValues<global::Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import.ImportPostResponse_failure_items_errors>("errors", Errors);
            writer.WriteCollectionOfPrimitiveValues<string>("industry_roles", IndustryRoles);
            writer.WriteStringValue("project_id", ProjectId);
            writer.WriteObjectValue<global::Autodesk.BIM360.Hq.V2.Regions.Eu.Accounts.Item.Projects.Item.Users.Import.ImportPostResponse_failure_items_services>("services", Services);
            writer.WriteStringValue("user_id", UserId);
        }
    }
}
#pragma warning restore CS0618
