// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.BuildingConnected.Construction.Buildingconnected.V2.Invites.Item
{
    /// <summary>The type of inviter sending the bid invitation. Possible values: `HOST`, `BIDDER`, `PUBLIC`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithInviteGetResponse_invitees_inviterType
    {
        [EnumMember(Value = "HOST")]
        #pragma warning disable CS1591
        HOST,
        #pragma warning restore CS1591
        [EnumMember(Value = "BIDDER")]
        #pragma warning disable CS1591
        BIDDER,
        #pragma warning restore CS1591
        [EnumMember(Value = "PUBLIC")]
        #pragma warning disable CS1591
        PUBLIC,
        #pragma warning restore CS1591
    }
}
