// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.BIM360.Bim360.Relationship.V2.Utility.RelationshipsWritable
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RelationshipsWritableGetResponse_entityTypes : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The allow list for the entity type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Autodesk.BIM360.Bim360.Relationship.V2.Utility.RelationshipsWritable.RelationshipsWritableGetResponse_entityTypes_allow>? Allow { get; set; }
#nullable restore
#else
        public List<global::Autodesk.BIM360.Bim360.Relationship.V2.Utility.RelationshipsWritable.RelationshipsWritableGetResponse_entityTypes_allow> Allow { get; set; }
#endif
        /// <summary>An individual entity type.For example: ``asset``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntityType { get; set; }
#nullable restore
#else
        public string EntityType { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.BIM360.Bim360.Relationship.V2.Utility.RelationshipsWritable.RelationshipsWritableGetResponse_entityTypes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.BIM360.Bim360.Relationship.V2.Utility.RelationshipsWritable.RelationshipsWritableGetResponse_entityTypes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.BIM360.Bim360.Relationship.V2.Utility.RelationshipsWritable.RelationshipsWritableGetResponse_entityTypes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow", n => { Allow = n.GetCollectionOfObjectValues<global::Autodesk.BIM360.Bim360.Relationship.V2.Utility.RelationshipsWritable.RelationshipsWritableGetResponse_entityTypes_allow>(global::Autodesk.BIM360.Bim360.Relationship.V2.Utility.RelationshipsWritable.RelationshipsWritableGetResponse_entityTypes_allow.CreateFromDiscriminatorValue)?.AsList(); } },
                { "entityType", n => { EntityType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Autodesk.BIM360.Bim360.Relationship.V2.Utility.RelationshipsWritable.RelationshipsWritableGetResponse_entityTypes_allow>("allow", Allow);
            writer.WriteStringValue("entityType", EntityType);
        }
    }
}
#pragma warning restore CS0618
