// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \construction\buildingconnected\v2\opportunity-project-pairs\{opportunityProjectPairId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithOpportunityProjectPairItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOpportunityProjectPairItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/construction/buildingconnected/v2/opportunity-project-pairs/{opportunityProjectPairId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOpportunityProjectPairItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/construction/buildingconnected/v2/opportunity-project-pairs/{opportunityProjectPairId}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves the specified opportunity-project pair.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairGetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairGetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairGetResponse>(requestInfo, global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Relinks a project from an opportunity group child that it&apos;s paired with to the group parent. The link between the project and the child opportunity is removed.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairPatchResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairPatchResponse?> PatchAsync(global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairPatchResponse> PatchAsync(global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairPatchResponse>(requestInfo, global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairPatchResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves the specified opportunity-project pair.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Relinks a project from an opportunity group child that it&apos;s paired with to the group parent. The link between the project and the child opportunity is removed.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairPatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Autodesk.BuildingConnected.Construction.Buildingconnected.V2.OpportunityProjectPairs.Item.WithOpportunityProjectPairItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
