// <auto-generated/>
#pragma warning disable CS0618
using Autodesk.BIM360.Bim360.Rfis.V2.Containers.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Autodesk.BIM360.Bim360.Rfis.V2.Containers
{
    /// <summary>
    /// Builds and executes requests for operations under \bim360\rfis\v2\containers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContainersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Autodesk.BIM360.bim360.rfis.v2.containers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Autodesk.BIM360.Bim360.Rfis.V2.Containers.Item.WithContainerItemRequestBuilder"/></returns>
        public global::Autodesk.BIM360.Bim360.Rfis.V2.Containers.Item.WithContainerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("containerId", position);
                return new global::Autodesk.BIM360.Bim360.Rfis.V2.Containers.Item.WithContainerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.BIM360.Bim360.Rfis.V2.Containers.ContainersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContainersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bim360/rfis/v2/containers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.BIM360.Bim360.Rfis.V2.Containers.ContainersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContainersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bim360/rfis/v2/containers", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
