// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.BIM360.Issues.V2.Containers.Item.Users.Me
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MeGetResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Not relevant</summary>
        public bool? CanManageTemplates { get; set; }
        /// <summary>The user&apos;s Autodesk ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>States whether the current logged in user is a system admin.</summary>
        public bool? IsProjectAdmin { get; set; }
        /// <summary>The issues property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Autodesk.BIM360.Issues.V2.Containers.Item.Users.Me.MeGetResponse_issues>? Issues { get; set; }
#nullable restore
#else
        public List<global::Autodesk.BIM360.Issues.V2.Containers.Item.Users.Me.MeGetResponse_issues> Issues { get; set; }
#endif
        /// <summary>The permission level of the user in the current project.You can also verify a user&apos;s assignment permissions by checking the ``permittedActions`` or ``permissionLevels`` attributes.Each permission level corresponds to a combination of values in the response.- View All: ``read`` - Can view the &apos;data:read&apos; only endpoints.- Create: ``create`` - Can create for my company.- View and Create: ``read``, ``create`` - Can create for other companies.- Full control: ``create``, ``read``, ``write`` - Can manage issues.Possible values: ``create``, ``read``, ``write``</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PermissionLevels { get; set; }
#nullable restore
#else
        public List<string> PermissionLevels { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.BIM360.Issues.V2.Containers.Item.Users.Me.MeGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.BIM360.Issues.V2.Containers.Item.Users.Me.MeGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.BIM360.Issues.V2.Containers.Item.Users.Me.MeGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "canManageTemplates", n => { CanManageTemplates = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isProjectAdmin", n => { IsProjectAdmin = n.GetBoolValue(); } },
                { "issues", n => { Issues = n.GetCollectionOfObjectValues<global::Autodesk.BIM360.Issues.V2.Containers.Item.Users.Me.MeGetResponse_issues>(global::Autodesk.BIM360.Issues.V2.Containers.Item.Users.Me.MeGetResponse_issues.CreateFromDiscriminatorValue)?.AsList(); } },
                { "permissionLevels", n => { PermissionLevels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("canManageTemplates", CanManageTemplates);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isProjectAdmin", IsProjectAdmin);
            writer.WriteCollectionOfObjectValues<global::Autodesk.BIM360.Issues.V2.Containers.Item.Users.Me.MeGetResponse_issues>("issues", Issues);
            writer.WriteCollectionOfPrimitiveValues<string>("permissionLevels", PermissionLevels);
        }
    }
}
#pragma warning restore CS0618
