// <auto-generated/>
#pragma warning disable CS0618
using Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.Collections;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \parameters\v1\accounts\{accountId}\groups\{groupId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithGroupItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The collections property</summary>
        public global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.Collections.CollectionsRequestBuilder Collections
        {
            get => new global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.Collections.CollectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGroupItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/parameters/v1/accounts/{accountId}/groups/{groupId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGroupItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/parameters/v1/accounts/{accountId}/groups/{groupId}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the details of the specified group, including details of your access level to this group.
        /// Online documentation <see href="https://aps.autodesk.com/en/docs/parameters/v1/reference/http/parameters-getgroup-GET" />
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupGetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupGetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupGetResponse>(requestInfo, global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update the details of an existing group. The title cannot be empty or null.
        /// Online documentation <see href="https://aps.autodesk.com/en/docs/parameters/v1/reference/http/parameters-updategroup-PUT" />
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupPutResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupPutResponse?> PutAsync(global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupPutResponse> PutAsync(global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupPutResponse>(requestInfo, global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupPutResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the details of the specified group, including details of your access level to this group.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update the details of an existing group. The title cannot be empty or null.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Autodesk.Parameters.Parameters.V1.Accounts.Item.Groups.Item.WithGroupItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
