// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases
{
    /// <summary>Defines this input parameter to be of numeric type. Will always be: `NUMERIC`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ReleasesPostResponse_parameters_oneOf_NumericInput_type
    {
        [EnumMember(Value = "NUMERIC")]
        #pragma warning disable CS1591
        NUMERIC,
        #pragma warning restore CS1591
    }
}
