// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.BIM360.Cost.V1.Containers.Item.TimeSheets.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TimeSheetsPatchResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The BIM 360/ACC ID of the user who made the last change to the timesheet.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChangedBy { get; set; }
#nullable restore
#else
        public string ChangedBy { get; set; }
#endif
        /// <summary>The ID of the cost container for the project to which the timesheet belongs.</summary>
        public Guid? ContainerId { get; set; }
        /// <summary>The date and time that the item was created, in ISO 8601 format.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The BIM 360/ACC ID of the user who created the timesheet.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorId { get; set; }
#nullable restore
#else
        public string CreatorId { get; set; }
#endif
        /// <summary>The last date of the time period covered by the timesheet. This is also the date that the tracked ``inputQuantity`` and ``outputQuantity`` values are considered to have been reported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndDate { get; set; }
#nullable restore
#else
        public string EndDate { get; set; }
#endif
        /// <summary>The ID of the timesheet.</summary>
        public Guid? Id { get; set; }
        /// <summary>The hours worked during the time period covered by the timesheet.</summary>
        public double? InputQuantity { get; set; }
        /// <summary>The input unit of measurement of the timesheet. Currently this value should always be ``hr``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InputUnit { get; set; }
#nullable restore
#else
        public string InputUnit { get; set; }
#endif
        /// <summary>The quantity of material used during time period covered by the timesheet.</summary>
        public double? OutputQuantity { get; set; }
        /// <summary>The output unit of measurement of the timesheet.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutputUnit { get; set; }
#nullable restore
#else
        public string OutputUnit { get; set; }
#endif
        /// <summary>The first date of the time period covered by the timesheet.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartDate { get; set; }
#nullable restore
#else
        public string StartDate { get; set; }
#endif
        /// <summary>The ID of the tracking item instance to which the timesheet belongs.</summary>
        public Guid? TrackingItemInstanceId { get; set; }
        /// <summary>The date and time that the item was last updated, in ISO 8601 format.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.BIM360.Cost.V1.Containers.Item.TimeSheets.Item.TimeSheetsPatchResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.BIM360.Cost.V1.Containers.Item.TimeSheets.Item.TimeSheetsPatchResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.BIM360.Cost.V1.Containers.Item.TimeSheets.Item.TimeSheetsPatchResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "changedBy", n => { ChangedBy = n.GetStringValue(); } },
                { "containerId", n => { ContainerId = n.GetGuidValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "creatorId", n => { CreatorId = n.GetStringValue(); } },
                { "endDate", n => { EndDate = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "inputQuantity", n => { InputQuantity = n.GetDoubleValue(); } },
                { "inputUnit", n => { InputUnit = n.GetStringValue(); } },
                { "outputQuantity", n => { OutputQuantity = n.GetDoubleValue(); } },
                { "outputUnit", n => { OutputUnit = n.GetStringValue(); } },
                { "startDate", n => { StartDate = n.GetStringValue(); } },
                { "trackingItemInstanceId", n => { TrackingItemInstanceId = n.GetGuidValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("changedBy", ChangedBy);
            writer.WriteGuidValue("containerId", ContainerId);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("creatorId", CreatorId);
            writer.WriteStringValue("endDate", EndDate);
            writer.WriteGuidValue("id", Id);
            writer.WriteDoubleValue("inputQuantity", InputQuantity);
            writer.WriteStringValue("inputUnit", InputUnit);
            writer.WriteDoubleValue("outputQuantity", OutputQuantity);
            writer.WriteStringValue("outputUnit", OutputUnit);
            writer.WriteStringValue("startDate", StartDate);
            writer.WriteGuidValue("trackingItemInstanceId", TrackingItemInstanceId);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
        }
    }
}
#pragma warning restore CS0618
