// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Metadata
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MetadataGetResponse_responses : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The type of response. Possible values: ``1`` (Approved), ``2`` (Revise and submit), ``3`` (Rejected).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CategoryId { get; set; }
#nullable restore
#else
        public string CategoryId { get; set; }
#endif
        /// <summary>The time and date when the response was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The Autodesk ID of the user who created the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The internal, globally unique identifier (UUID) for the response.</summary>
        public Guid? Id { get; set; }
        /// <summary>``true``: if the response was not deleted.``false``: if the response was deleted.</summary>
        public bool? IsActive { get; set; }
        /// <summary>``true``: settings this response for a submittal item means an approval.``false``: settings this response for a submittal item means dis-approval.This attribute is taken from the related categoryId</summary>
        public bool? IsApproval { get; set; }
        /// <summary>``true``: if the response is currently associated with a submittal item.``false``: if the response is not currently associated with a submittal item.</summary>
        public bool? IsInUse { get; set; }
        /// <summary>Not relevant</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>Not relevant</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlatformId { get; set; }
#nullable restore
#else
        public string PlatformId { get; set; }
#endif
        /// <summary>The time and date when the response was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The Autodesk ID of the user who last updated the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedBy { get; set; }
#nullable restore
#else
        public string UpdatedBy { get; set; }
#endif
        /// <summary>The content of the response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Metadata.MetadataGetResponse_responses"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Metadata.MetadataGetResponse_responses CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Metadata.MetadataGetResponse_responses();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "categoryId", n => { CategoryId = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isActive", n => { IsActive = n.GetBoolValue(); } },
                { "isApproval", n => { IsApproval = n.GetBoolValue(); } },
                { "isInUse", n => { IsInUse = n.GetBoolValue(); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "platformId", n => { PlatformId = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "updatedBy", n => { UpdatedBy = n.GetStringValue(); } },
                { "value", n => { Value = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("categoryId", CategoryId);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteBoolValue("isApproval", IsApproval);
            writer.WriteBoolValue("isInUse", IsInUse);
            writer.WriteStringValue("key", Key);
            writer.WriteStringValue("platformId", PlatformId);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteStringValue("updatedBy", UpdatedBy);
            writer.WriteStringValue("value", Value);
        }
    }
}
#pragma warning restore CS0618
