// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.ACC.Bim360.Modelset.V3.Containers.Item.Modelsets.Item.Views
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ViewsGetResponse_modelSetViews_definition : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The lineage URN of the seed file or document lineage to track with this view. Min length: 1 Max length: 80.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LineageUrn { get; set; }
#nullable restore
#else
        public string LineageUrn { get; set; }
#endif
        /// <summary>The name of the viewable in the Model Derivative manifest to track along the seed file lineage. This value is ignored if ``lineageUrn`` is the URN of a BIM360 Docs Plans folder document. Min length: 1 Max length: 430.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ViewableName { get; set; }
#nullable restore
#else
        public string ViewableName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Bim360.Modelset.V3.Containers.Item.Modelsets.Item.Views.ViewsGetResponse_modelSetViews_definition"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.ACC.Bim360.Modelset.V3.Containers.Item.Modelsets.Item.Views.ViewsGetResponse_modelSetViews_definition CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.ACC.Bim360.Modelset.V3.Containers.Item.Modelsets.Item.Views.ViewsGetResponse_modelSetViews_definition();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "lineageUrn", n => { LineageUrn = n.GetStringValue(); } },
                { "viewableName", n => { ViewableName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("lineageUrn", LineageUrn);
            writer.WriteStringValue("viewableName", ViewableName);
        }
    }
}
#pragma warning restore CS0618
