// <auto-generated/>
#pragma warning disable CS0618
using Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews
{
    /// <summary>
    /// Builds and executes requests for operations under \construction\reviews\v1\projects\{projectId}\reviews
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReviewsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Autodesk.ACC.construction.reviews.v1.projects.item.reviews.item collection</summary>
        /// <param name="position">The unique ID of the review.It must be in UUID format — not the numeric sequence ID shown in the Reviews UI. To find the review ID, call `GET reviews &lt;en/docs/acc/v1/reference/http/reviews-reviews-GET/&gt;`_.</param>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.Item.WithReviewItemRequestBuilder"/></returns>
        public global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.Item.WithReviewItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("reviewId", position);
                return new global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.Item.WithReviewItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Autodesk.ACC.construction.reviews.v1.projects.item.reviews.item collection</summary>
        /// <param name="position">The unique ID of the review.It must be in UUID format — not the numeric sequence ID shown in the Reviews UI. To find the review ID, call `GET reviews &lt;en/docs/acc/v1/reference/http/reviews-reviews-GET/&gt;`_.</param>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.Item.WithReviewItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.Item.WithReviewItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("reviewId", position);
                return new global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.Item.WithReviewItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReviewsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/construction/reviews/v1/projects/{projectId}/reviews{?filter%5BarchivedAt%5D*,filter%5BarchivedBy%5D*,filter%5Barchived%5D*,filter%5BcreatedAt%5D*,filter%5BcurrentStepDueDate%5D*,filter%5BfinishedAt%5D*,filter%5Bname%5D*,filter%5BnextActionByCompany%5D*,filter%5BnextActionByRole%5D*,filter%5BnextActionByUser%5D*,filter%5BsequenceId%5D*,filter%5Bstatus%5D*,filter%5BupdatedAt%5D*,filter%5BworkflowId%5D*,limit*,offset*,sort*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReviewsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/construction/reviews/v1/projects/{projectId}/reviews{?filter%5BarchivedAt%5D*,filter%5BarchivedBy%5D*,filter%5Barchived%5D*,filter%5BcreatedAt%5D*,filter%5BcurrentStepDueDate%5D*,filter%5BfinishedAt%5D*,filter%5Bname%5D*,filter%5BnextActionByCompany%5D*,filter%5BnextActionByRole%5D*,filter%5BnextActionByUser%5D*,filter%5BsequenceId%5D*,filter%5Bstatus%5D*,filter%5BupdatedAt%5D*,filter%5BworkflowId%5D*,limit*,offset*,sort*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves the list of reviews created in the specified project.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsGetResponse?> GetAsReviewsGetResponseAsync(Action<RequestConfiguration<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsRequestBuilder.ReviewsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsGetResponse> GetAsReviewsGetResponseAsync(Action<RequestConfiguration<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsRequestBuilder.ReviewsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsGetResponse>(requestInfo, global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves the list of reviews created in the specified project.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsReviewsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsResponse?> GetAsync(Action<RequestConfiguration<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsRequestBuilder.ReviewsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsResponse> GetAsync(Action<RequestConfiguration<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsRequestBuilder.ReviewsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsResponse>(requestInfo, global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new review in the specified project using an existing approval workflow.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsPostResponse?> PostAsReviewsPostResponseAsync(global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsPostResponse> PostAsReviewsPostResponseAsync(global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsPostResponse>(requestInfo, global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new review in the specified project using an existing approval workflow.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsReviewsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsResponse?> PostAsync(global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsResponse> PostAsync(global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsResponse>(requestInfo, global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves the list of reviews created in the specified project.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsRequestBuilder.ReviewsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsRequestBuilder.ReviewsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new review in the specified project using an existing approval workflow.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves the list of reviews created in the specified project.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReviewsRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter by archive status in URL-encoded format.``true``: retrieves only archived reviews.``false``: retrieves only active (non-archived) reviews.If omitted, only active reviews are retrieved.For example: ``filter[archived]=false``.</summary>
            [QueryParameter("filter%5Barchived%5D")]
            public bool? Filterarchived { get; set; }
            /// <summary>Filter by the date the review was archived, in URL-encoded format.It only applies if ``filter[archived]=true``.Provide a date range using the format ``startDate..endDate``.Both values must be in ISO 8601 format.For example: ``filter[archivedAt]=2023-06-01..2023-06-30``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5BarchivedAt%5D")]
            public string? FilterarchivedAt { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5BarchivedAt%5D")]
            public string FilterarchivedAt { get; set; }
#endif
            /// <summary>Filter by the Autodesk ID of the user who archived the review, in URL-encoded format. To find the ID, call `GET users &lt;/en/docs/acc/v1/reference/http/admin-projectsprojectId-users-GET/&gt;`_.It only takes effect when ``filter[archived]=true`` is also set.For example: ``filter[archivedBy]=A96JX8NUKRLVFWSR``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5BarchivedBy%5D")]
            public string? FilterarchivedBy { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5BarchivedBy%5D")]
            public string FilterarchivedBy { get; set; }
#endif
            /// <summary>Filter by review creation date in URL-encoded format.Provide a date range using the format ``startDate..endDate``.Both values must be in ISO 8601 format.For example: ``filter[createdAt]=2023-06-01..2023-06-30``</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5BcreatedAt%5D")]
            public string? FiltercreatedAt { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5BcreatedAt%5D")]
            public string FiltercreatedAt { get; set; }
#endif
            /// <summary>Filter by the due date of the current review step in URL-encoded format.Provide a date range using the format ``startDate..endDate``.Both values must be in ISO 8601 format.For example: ``filter[updatedAt]=2023-06-01..2023-06-30``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5BcurrentStepDueDate%5D")]
            public string? FiltercurrentStepDueDate { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5BcurrentStepDueDate%5D")]
            public string FiltercurrentStepDueDate { get; set; }
#endif
            /// <summary>Filter by the date the review was finished, in URL-encoded format.Provide a date range using the format ``startDate..endDate``.Both values must be in ISO 8601 format.For example: ``filter[finishedAt]=2023-06-01..2023-06-30``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5BfinishedAt%5D")]
            public string? FilterfinishedAt { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5BfinishedAt%5D")]
            public string FilterfinishedAt { get; set; }
#endif
            /// <summary>Filter by review name in URL-encoded format.Retrieves reviews with names that contain the specified string (not case-sensitive).For example: ``filter[name]=Apartment`` retrieves reviews like ``Apartment Block A`` and ``apartment_rendering``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bname%5D")]
            public string? Filtername { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bname%5D")]
            public string Filtername { get; set; }
#endif
            /// <summary>Filter by Autodesk ID of a company responsible for the next action, in URL-encoded format.For example: ``filter[nextActionByCompany]=81768771``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5BnextActionByCompany%5D")]
            public string? FilternextActionByCompany { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5BnextActionByCompany%5D")]
            public string FilternextActionByCompany { get; set; }
#endif
            /// <summary>Filter by Autodesk ID of a role responsible for the next action, in URL-encoded format.For example: ``filter[nextActionByRole]=1572818``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5BnextActionByRole%5D")]
            public string? FilternextActionByRole { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5BnextActionByRole%5D")]
            public string FilternextActionByRole { get; set; }
#endif
            /// <summary>Filter by Autodesk ID of a user responsible for the next action, in URL-encoded format.This includes reviews assigned directly to the user or to their role or company.For example: ``filter[nextActionByUser]=A96JX8NUKRLVFWSR``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5BnextActionByUser%5D")]
            public string? FilternextActionByUser { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5BnextActionByUser%5D")]
            public string FilternextActionByUser { get; set; }
#endif
            /// <summary>Filter by review sequence ID in URL-encoded format.Retrieves reviews with sequence IDs that partially match the specified number.For example: ``filter[sequenceId]=11`` may retrieve ``113`` and ``211``.</summary>
            [QueryParameter("filter%5BsequenceId%5D")]
            public int? FiltersequenceId { get; set; }
            /// <summary>Filter by the review status in URL-encoded format.Possible values: ``OPEN``, ``CLOSED``, ``VOID``, ``FAILED``.For example: ``filter[status]=OPEN``.Reviews with status ``FAILED`` are only visible to project administrators.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Bstatus%5D")]
            public string? Filterstatus { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Bstatus%5D")]
            public string Filterstatus { get; set; }
#endif
            /// <summary>Filter by the review’s last updated date in URL-encoded format.Provide a date range using the format ``startDate..endDate``.Both values must be in ISO 8601 format.For example: ``filter[updatedAt]=2023-06-01..2023-06-30``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5BupdatedAt%5D")]
            public string? FilterupdatedAt { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5BupdatedAt%5D")]
            public string FilterupdatedAt { get; set; }
#endif
            /// <summary>Filter by a specific approval workflow ID in URL-encoded format.For example: ``filter[workflowId]=497f6eca-6276-4993-bfeb-53cbbbba6f08``.</summary>
            [QueryParameter("filter%5BworkflowId%5D")]
            public Guid? FilterworkflowId { get; set; }
            /// <summary>The maximum number of reviews to retrieve.Possible values: ``1-50``. Maximum: ``50``. Default: ``50``. For example: ``limit=2``.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>The index of the first result to return (zero-based).Default: ``0``. For example: ``offset=10``.</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            /// <summary>Sorts the results by a single field.Use the format ``fieldName`` (ascending) or ``fieldName desc`` (descending).If no direction is specified, sorting defaults to ascending.Possible values: ``name``, ``status``, ``sequenceId``, ``currentStepDueDate``, ``createdAt``, ``finishedAt``.For example: ``sort=createdAt desc``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReviewsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.ReviewsRequestBuilder.ReviewsRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReviewsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
