// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Rfis.Item.Responses.Item
{
    /// <summary>The state of the response. Possible values:- ``draft``: The response was returned to the reviewer for changes.- ``submitted``: The reviewer submitted a finalized response.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithResponsePatchResponse_rfi_responses_state
    {
        [EnumMember(Value = "draft")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "submitted")]
        #pragma warning disable CS1591
        Submitted,
        #pragma warning restore CS1591
    }
}
