// <auto-generated/>
#pragma warning disable CS0618
using Autodesk.ACC.Construction.Issues.V1.Projects.Item.Attachments;
using Autodesk.ACC.Construction.Issues.V1.Projects.Item.IssueAttributeDefinitions;
using Autodesk.ACC.Construction.Issues.V1.Projects.Item.IssueAttributeMappings;
using Autodesk.ACC.Construction.Issues.V1.Projects.Item.IssueRootCauseCategories;
using Autodesk.ACC.Construction.Issues.V1.Projects.Item.IssueTypes;
using Autodesk.ACC.Construction.Issues.V1.Projects.Item.Issues;
using Autodesk.ACC.Construction.Issues.V1.Projects.Item.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Autodesk.ACC.Construction.Issues.V1.Projects.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \construction\issues\v1\projects\{projectId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProjectItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The attachments property</summary>
        public global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.Attachments.AttachmentsRequestBuilder Attachments
        {
            get => new global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.Attachments.AttachmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issueAttributeDefinitions property</summary>
        public global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.IssueAttributeDefinitions.IssueAttributeDefinitionsRequestBuilder IssueAttributeDefinitions
        {
            get => new global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.IssueAttributeDefinitions.IssueAttributeDefinitionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issueAttributeMappings property</summary>
        public global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.IssueAttributeMappings.IssueAttributeMappingsRequestBuilder IssueAttributeMappings
        {
            get => new global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.IssueAttributeMappings.IssueAttributeMappingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issueRootCauseCategories property</summary>
        public global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.IssueRootCauseCategories.IssueRootCauseCategoriesRequestBuilder IssueRootCauseCategories
        {
            get => new global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.IssueRootCauseCategories.IssueRootCauseCategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issues property</summary>
        public global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.Issues.IssuesRequestBuilder Issues
        {
            get => new global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.Issues.IssuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issueTypes property</summary>
        public global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.IssueTypes.IssueTypesRequestBuilder IssueTypes
        {
            get => new global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.IssueTypes.IssueTypesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.Users.UsersRequestBuilder Users
        {
            get => new global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.WithProjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/construction/issues/v1/projects/{projectId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.Construction.Issues.V1.Projects.Item.WithProjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/construction/issues/v1/projects/{projectId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
