// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.ACC.Construction.Forms.V1.Projects.Item.Forms.Item.ValuesBatchUpdate
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ValuesBatchUpdatePutRequestBody_customValues : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The attribute used for updating multi-select fields. For example, ``arrayVal:`` ``[``Answer 1``, ``Answer 2``]``.Each non-tabular field is assigned a specific value type, which you need to specify when updating the field. ``arrayVal`` is only relevant for updating multi-select fields. To verify whether the field you want to update is a multi-select field, call GET forms and check the field&apos;s ``valueName``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ArrayVal { get; set; }
#nullable restore
#else
        public List<string> ArrayVal { get; set; }
#endif
        /// <summary>The attribute used for updating single-select and dropdown fields. For example, ``choiceVal: Answer 3``.Each non-tabular field is assigned a specific value type, which you need to specify when updating the field. ``choiceVal`` is only relevant for updating single-select and dropdown fields. To verify whether the field you want to update is a single-select or dropdown field, call GET forms and check the field&apos;s ``valueName``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChoiceVal { get; set; }
#nullable restore
#else
        public string ChoiceVal { get; set; }
#endif
        /// <summary>The attribute used for updating date fields, in the following format ``(YYYY-MM-DD)``. For example, ````dateVal``: ``1999-12-31````.Each non-tabular field is assigned a specific value type, which you need to specify when updating the field. ``dateVal`` is only relevant for updating date fields. To verify whether the field you want to update is a date field, call GET forms and check the field&apos;s ``valueName``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateVal { get; set; }
#nullable restore
#else
        public string DateVal { get; set; }
#endif
        /// <summary>The unique identifier of the field.</summary>
        public Guid? FieldId { get; set; }
        /// <summary>The name of the person who signed the form. By default, it is the name of the logged in user. It is only relevant for signature fields. To update the name you need to use the signature field ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Text for the field&apos;s notes section. This is relevant for all fields.Max length: 8000</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The attribute used for updating number fields. For example, ````numberVal``: ``42````.Each non-tabular field is assigned a specific value type, which you need to specify when updating the field. ``numberVal`` is only relevant for updating number fields. To verify whether the field you want to update is a number field, call GET forms and check the field&apos;s ``valueName``.</summary>
        public double? NumberVal { get; set; }
        /// <summary>The attribute used for updating signature fields.Each non-tabular field is assigned a specific value type, which you need to specify when updating the field. ``svgVal`` is only relevant for updating signature fields. To verify whether the field you want to update is a signature field, call GET forms and check the field&apos;s ``valueName``.The signature needs to be in SVG format and it needs to be base64 encoded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SvgVal { get; set; }
#nullable restore
#else
        public string SvgVal { get; set; }
#endif
        /// <summary>The attribute used for updating text value fields, For example, ``textVal: This is my response!``.Each non-tabular field is assigned a specific value type, which you need to specify when updating the field. ``textVal`` is only relevant for updating text value fields. To verify whether the field you want to update is a text value field, call GET forms and check the field&apos;s ``valueName``.Max length: 8000</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TextVal { get; set; }
#nullable restore
#else
        public string TextVal { get; set; }
#endif
        /// <summary>The attribute used for updating preconfigured fields. For example, ``toggleVal``: ``Yes``.Each non-tabular field is assigned a specific value type, which you need to specify when updating the field. ``toggleVal`` is only relevant for updating preconfigured fields. To verify whether the field you want to update is a preconfigured field, call GET forms and check the field&apos;s ``valueName``.Possible values: ``Yes``, ``No``, ``False``, ``True``, ``Minus``, ``Plus``, ``Fail``, ``Pass``, ``NA``</summary>
        public global::Autodesk.ACC.Construction.Forms.V1.Projects.Item.Forms.Item.ValuesBatchUpdate.ValuesBatchUpdatePutRequestBody_customValues_toggleVal? ToggleVal { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Forms.V1.Projects.Item.Forms.Item.ValuesBatchUpdate.ValuesBatchUpdatePutRequestBody_customValues"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.ACC.Construction.Forms.V1.Projects.Item.Forms.Item.ValuesBatchUpdate.ValuesBatchUpdatePutRequestBody_customValues CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.ACC.Construction.Forms.V1.Projects.Item.Forms.Item.ValuesBatchUpdate.ValuesBatchUpdatePutRequestBody_customValues();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "arrayVal", n => { ArrayVal = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "choiceVal", n => { ChoiceVal = n.GetStringValue(); } },
                { "dateVal", n => { DateVal = n.GetStringValue(); } },
                { "fieldId", n => { FieldId = n.GetGuidValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "numberVal", n => { NumberVal = n.GetDoubleValue(); } },
                { "svgVal", n => { SvgVal = n.GetStringValue(); } },
                { "textVal", n => { TextVal = n.GetStringValue(); } },
                { "toggleVal", n => { ToggleVal = n.GetEnumValue<global::Autodesk.ACC.Construction.Forms.V1.Projects.Item.Forms.Item.ValuesBatchUpdate.ValuesBatchUpdatePutRequestBody_customValues_toggleVal>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("arrayVal", ArrayVal);
            writer.WriteStringValue("choiceVal", ChoiceVal);
            writer.WriteStringValue("dateVal", DateVal);
            writer.WriteGuidValue("fieldId", FieldId);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("notes", Notes);
            writer.WriteDoubleValue("numberVal", NumberVal);
            writer.WriteStringValue("svgVal", SvgVal);
            writer.WriteStringValue("textVal", TextVal);
            writer.WriteEnumValue<global::Autodesk.ACC.Construction.Forms.V1.Projects.Item.Forms.Item.ValuesBatchUpdate.ValuesBatchUpdatePutRequestBody_customValues_toggleVal>("toggleVal", ToggleVal);
        }
    }
}
#pragma warning restore CS0618
