// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PropertiesGetResponse_prev : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>maximum [x, y, z]-coords of the 3D-bbox.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? BboxMax { get; set; }
#nullable restore
#else
        public List<int?> BboxMax { get; set; }
#endif
        /// <summary>minimum [x, y, z]-coords of the 3D-bbox.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? BboxMin { get; set; }
#nullable restore
#else
        public List<int?> BboxMin { get; set; }
#endif
        /// <summary>Property database id (the property database the object originated from).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DbId { get; set; }
#nullable restore
#else
        public string DbId { get; set; }
#endif
        /// <summary>Hash used to determine whether the object geometry has changed between different versions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GeomHash { get; set; }
#nullable restore
#else
        public string GeomHash { get; set; }
#endif
        /// <summary>Object database id from the original seed file property database (_objects_id.id).</summary>
        public int? LmvId { get; set; }
        /// <summary>Property database property keyed values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties.PropertiesGetResponse_prev_props? Props { get; set; }
#nullable restore
#else
        public global::Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties.PropertiesGetResponse_prev_props Props { get; set; }
#endif
        /// <summary>Hash used to determine whether object properties have changed between different versions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PropsHash { get; set; }
#nullable restore
#else
        public string PropsHash { get; set; }
#endif
        /// <summary>Property database property values that are not considered for property change tracking.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties.PropertiesGetResponse_prev_propsIgnored? PropsIgnored { get; set; }
#nullable restore
#else
        public global::Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties.PropertiesGetResponse_prev_propsIgnored PropsIgnored { get; set; }
#endif
        /// <summary>List of corresponding view IDs in the index manifest that this object is visible in.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Views { get; set; }
#nullable restore
#else
        public List<string> Views { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties.PropertiesGetResponse_prev"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties.PropertiesGetResponse_prev CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties.PropertiesGetResponse_prev();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bboxMax", n => { BboxMax = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "bboxMin", n => { BboxMin = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "dbId", n => { DbId = n.GetStringValue(); } },
                { "geomHash", n => { GeomHash = n.GetStringValue(); } },
                { "lmvId", n => { LmvId = n.GetIntValue(); } },
                { "props", n => { Props = n.GetObjectValue<global::Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties.PropertiesGetResponse_prev_props>(global::Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties.PropertiesGetResponse_prev_props.CreateFromDiscriminatorValue); } },
                { "propsHash", n => { PropsHash = n.GetStringValue(); } },
                { "propsIgnored", n => { PropsIgnored = n.GetObjectValue<global::Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties.PropertiesGetResponse_prev_propsIgnored>(global::Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties.PropertiesGetResponse_prev_propsIgnored.CreateFromDiscriminatorValue); } },
                { "views", n => { Views = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<int?>("bboxMax", BboxMax);
            writer.WriteCollectionOfPrimitiveValues<int?>("bboxMin", BboxMin);
            writer.WriteStringValue("dbId", DbId);
            writer.WriteStringValue("geomHash", GeomHash);
            writer.WriteIntValue("lmvId", LmvId);
            writer.WriteObjectValue<global::Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties.PropertiesGetResponse_prev_props>("props", Props);
            writer.WriteStringValue("propsHash", PropsHash);
            writer.WriteObjectValue<global::Autodesk.ACC.Construction.IndexNamespace.V2.Projects.Item.Diffs.Item.Properties.PropertiesGetResponse_prev_propsIgnored>("propsIgnored", PropsIgnored);
            writer.WriteCollectionOfPrimitiveValues<string>("views", Views);
        }
    }
}
#pragma warning restore CS0618
