// <auto-generated/>
#pragma warning disable CS0618
using Autodesk.ACC.Construction.Rcm.V1.Projects.Item.PublishedVersions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Autodesk.ACC.Construction.Rcm.V1.Projects.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \construction\rcm\v1\projects\{projectId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProjectItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The publishedVersions property</summary>
        public global::Autodesk.ACC.Construction.Rcm.V1.Projects.Item.PublishedVersions.PublishedVersionsRequestBuilder PublishedVersions
        {
            get => new global::Autodesk.ACC.Construction.Rcm.V1.Projects.Item.PublishedVersions.PublishedVersionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.Construction.Rcm.V1.Projects.Item.WithProjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/construction/rcm/v1/projects/{projectId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.Construction.Rcm.V1.Projects.Item.WithProjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/construction/rcm/v1/projects/{projectId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
