// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.ACC.Construction.Forms.V1.Projects.Item.FormTemplates.Item.Forms
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FormsPostRequestBody : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Identifier of the company, role, or user assigned to the form. Note: the assignee must be a contributor of the template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssigneeId { get; set; }
#nullable restore
#else
        public string AssigneeId { get; set; }
#endif
        /// <summary>Type of entity to assign the form to.Possible values: ``company``, ``role``, ``user``</summary>
        public global::Autodesk.ACC.Construction.Forms.V1.Projects.Item.FormTemplates.Item.Forms.FormsPostRequestBody_assigneeType? AssigneeType { get; set; }
        /// <summary>Text for the form description field.Max length: 8000</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Date the form pertains to, must be after 1950-01-01.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FormDate { get; set; }
#nullable restore
#else
        public string FormDate { get; set; }
#endif
        /// <summary>The unique identifier of the form. If you do not specify an ID, one will be assigned.</summary>
        public Guid? Id { get; set; }
        /// <summary>Location associated with the Form. For more information about the location, see `GET nodes &lt;/en/docs/acc/v1/reference/http/locations-nodes-GET/&gt;`_.</summary>
        public Guid? LocationId { get; set; }
        /// <summary>The name of the form instance. If the specified value is ``null`` or empty, it defaults to the form&apos;s template name.Max length: 100</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Text for the form&apos;s notes section.Max length: 8000</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>Date and time indicating when form was created on the client or external system (optional).</summary>
        public DateTimeOffset? UserCreatedAt { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Forms.V1.Projects.Item.FormTemplates.Item.Forms.FormsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.ACC.Construction.Forms.V1.Projects.Item.FormTemplates.Item.Forms.FormsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.ACC.Construction.Forms.V1.Projects.Item.FormTemplates.Item.Forms.FormsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assigneeId", n => { AssigneeId = n.GetStringValue(); } },
                { "assigneeType", n => { AssigneeType = n.GetEnumValue<global::Autodesk.ACC.Construction.Forms.V1.Projects.Item.FormTemplates.Item.Forms.FormsPostRequestBody_assigneeType>(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "formDate", n => { FormDate = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "locationId", n => { LocationId = n.GetGuidValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "userCreatedAt", n => { UserCreatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("assigneeId", AssigneeId);
            writer.WriteEnumValue<global::Autodesk.ACC.Construction.Forms.V1.Projects.Item.FormTemplates.Item.Forms.FormsPostRequestBody_assigneeType>("assigneeType", AssigneeType);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("formDate", FormDate);
            writer.WriteGuidValue("id", Id);
            writer.WriteGuidValue("locationId", LocationId);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("notes", Notes);
            writer.WriteDateTimeOffsetValue("userCreatedAt", UserCreatedAt);
        }
    }
}
#pragma warning restore CS0618
