// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MeGetResponse_permittedActions : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>A mapping of field names to lists of possible values for each field, specific to the associated action. An empty array indicates that there is no specific set of values for those fields.For example, in the action ``Spec::create``, fields might contain mapping for title (``title``) and identifier (``identifier``).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me.MeGetResponse_permittedActions_fields? Fields { get; set; }
#nullable restore
#else
        public global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me.MeGetResponse_permittedActions_fields Fields { get; set; }
#endif
        /// <summary>ID of the action in the format ``type_of_object::action``. For example, ``item::create``, ``Spec::create``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>A subset of fields (``fields``) that are required to perform specific actions, such as creating or transitioning a submittal item. The required fields depend on the user’s role and the action.For example, creating a submittal item in the ``mgr-1`` state as a manager or in the ``sbc-1`` state as a subcontractor requires different fields. For example, [``stateId``, ``specId``, ``title``, ``typeId``, ``manager``, ``managerType``].</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MandatoryFields { get; set; }
#nullable restore
#else
        public List<string> MandatoryFields { get; set; }
#endif
        /// <summary>list of possible transitions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me.MeGetResponse_permittedActions_transitions>? Transitions { get; set; }
#nullable restore
#else
        public List<global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me.MeGetResponse_permittedActions_transitions> Transitions { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me.MeGetResponse_permittedActions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me.MeGetResponse_permittedActions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me.MeGetResponse_permittedActions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "fields", n => { Fields = n.GetObjectValue<global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me.MeGetResponse_permittedActions_fields>(global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me.MeGetResponse_permittedActions_fields.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "mandatoryFields", n => { MandatoryFields = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "transitions", n => { Transitions = n.GetCollectionOfObjectValues<global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me.MeGetResponse_permittedActions_transitions>(global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me.MeGetResponse_permittedActions_transitions.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me.MeGetResponse_permittedActions_fields>("fields", Fields);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfPrimitiveValues<string>("mandatoryFields", MandatoryFields);
            writer.WriteCollectionOfObjectValues<global::Autodesk.ACC.Construction.Submittals.V2.Projects.Item.Users.Me.MeGetResponse_permittedActions_transitions>("transitions", Transitions);
        }
    }
}
#pragma warning restore CS0618
