// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \industrialized-construction\informed-design\v1\downloads\{downloadRequestId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDownloadRequestItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDownloadRequestItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/industrialized-construction/informed-design/v1/downloads/{downloadRequestId}?accessId={accessId}&accessType={accessType}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDownloadRequestItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/industrialized-construction/informed-design/v1/downloads/{downloadRequestId}?accessId={accessId}&accessType={accessType}", rawUrl)
        {
        }
        /// <summary>
        /// Gets a download outputs request by ID.
        /// Online documentation <see href="https://aps.autodesk.com/en/docs/informed-design/v1/reference/quick_reference/informed-design-api-getdownloadoutputsrequestbyid-GET" />
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestGetResponse?> GetAsync(Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestItemRequestBuilder.WithDownloadRequestItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestGetResponse> GetAsync(Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestItemRequestBuilder.WithDownloadRequestItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestGetResponse>(requestInfo, global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets a download outputs request by ID.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestItemRequestBuilder.WithDownloadRequestItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestItemRequestBuilder.WithDownloadRequestItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.WithDownloadRequestItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets a download outputs request by ID.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithDownloadRequestItemRequestBuilderGetQueryParameters 
        {
            /// <summary>A composite string of identifiers that define the access scope for the given access type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("accessId")]
            public string? AccessId { get; set; }
#nullable restore
#else
            [QueryParameter("accessId")]
            public string AccessId { get; set; }
#endif
            /// <summary>The type of integration or service used to determine access context.Possible values: `ACC`, `BIM360`, `FUSION`, `CONTENTCATALOG`, `BRIDGE`, `PUBLIC`</summary>
            [QueryParameter("accessType")]
            public global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Downloads.Item.GetAccessTypeQueryParameterType? AccessType { get; set; }
        }
    }
}
#pragma warning restore CS0618
