// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances
{
    /// <summary>
    /// The attributes object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InstancesGetResponse_data_attributes : IParsable
    {
        /// <summary>* If ``true``, the user can be assigned to the checklist sections.* If ``false``, the user cannot be assigned to the checklist sections.</summary>
        public bool? AllowSectionAssignee { get; set; }
        /// <summary>A list of users who have been assigned to the checklist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_assignees>? Assignees { get; set; }
#nullable restore
#else
        public List<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_assignees> Assignees { get; set; }
#endif
        /// <summary>The number of completed checklist items.</summary>
        public double? CompletedItemsCount { get; set; }
        /// <summary>The date and time that the resource was created, in the following format: ``YYYY-MM-DDThh:mm:ss.sz``.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The Autodesk ID of the user who created the checklist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The date and time that the resource was deleted, in the following format: ``YYYY-MM-DDThh:mm:ss.sz``. This is used for offline mobile database managment.</summary>
        public DateTimeOffset? DeletedAt { get; set; }
        /// <summary>Not relevant</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstanceRevision { get; set; }
#nullable restore
#else
        public string InstanceRevision { get; set; }
#endif
        /// <summary>The description of the template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Instructions { get; set; }
#nullable restore
#else
        public string Instructions { get; set; }
#endif
        /// <summary>Not relevant</summary>
        public Guid? Location { get; set; }
        /// <summary>The Autodesk ID of the user who last modified the checklist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModifiedBy { get; set; }
#nullable restore
#else
        public string ModifiedBy { get; set; }
#endif
        /// <summary>A list of actions that the user is permitted to perform on the resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PermittedActions { get; set; }
#nullable restore
#else
        public List<string> PermittedActions { get; set; }
#endif
        /// <summary>A list of properties that a user with edit permission is allowed to modify.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PermittedAttributes { get; set; }
#nullable restore
#else
        public List<string> PermittedAttributes { get; set; }
#endif
        /// <summary>The percentage of checklist items that are completed; calculated using ``data.attributes.completedItemsCount`` and ``data.meta.totalItems``.</summary>
        public double? Progress { get; set; }
        /// <summary>The due date for the checklist, in the following format: ``YYYY-MM-DDThh:mm:ss.sz``.</summary>
        public DateTimeOffset? ScheduledDate { get; set; }
        /// <summary>A list of final signoff signatures.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_signatures>? Signatures { get; set; }
#nullable restore
#else
        public List<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_signatures> Signatures { get; set; }
#endif
        /// <summary>The signatures status of the checklist. Possible values:``Pending`` - all sections are complete but one or more signatures are required.``Required`` - not all sections are complete, and one or more signatures are required.``Signed`` - no more signatures are required.``None`` - signatures are not needed.</summary>
        public global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_signaturesStatus? SignaturesStatus { get; set; }
        /// <summary>Information about the status of the checklist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_status? Status { get; set; }
#nullable restore
#else
        public global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_status Status { get; set; }
#endif
        /// <summary>Information about the type of template.Possible values:``1`` - Quality``6`` - Punch List``11`` - Safety``15`` - Commissioning</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_templateType? TemplateType { get; set; }
#nullable restore
#else
        public global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_templateType TemplateType { get; set; }
#endif
        /// <summary>The version ID of the template associated with the checklist. Every time you update a template it updates the version ID.</summary>
        public int? TemplateVersionId { get; set; }
        /// <summary>The name of the checklist.Max length: 100</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Not relevant</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_trades>? Trades { get; set; }
#nullable restore
#else
        public List<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_trades> Trades { get; set; }
#endif
        /// <summary>The date and time that the resource was last updated, in the following format: ``YYYY-MM-DDThh:mm:ss.sz``.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>Not relevant</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Urn { get; set; }
#nullable restore
#else
        public string Urn { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowSectionAssignee", n => { AllowSectionAssignee = n.GetBoolValue(); } },
                { "assignees", n => { Assignees = n.GetCollectionOfObjectValues<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_assignees>(global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_assignees.CreateFromDiscriminatorValue)?.AsList(); } },
                { "completedItemsCount", n => { CompletedItemsCount = n.GetDoubleValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "deletedAt", n => { DeletedAt = n.GetDateTimeOffsetValue(); } },
                { "instanceRevision", n => { InstanceRevision = n.GetStringValue(); } },
                { "instructions", n => { Instructions = n.GetStringValue(); } },
                { "location", n => { Location = n.GetGuidValue(); } },
                { "modifiedBy", n => { ModifiedBy = n.GetStringValue(); } },
                { "permittedActions", n => { PermittedActions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "permittedAttributes", n => { PermittedAttributes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "progress", n => { Progress = n.GetDoubleValue(); } },
                { "scheduledDate", n => { ScheduledDate = n.GetDateTimeOffsetValue(); } },
                { "signatures", n => { Signatures = n.GetCollectionOfObjectValues<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_signatures>(global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_signatures.CreateFromDiscriminatorValue)?.AsList(); } },
                { "signaturesStatus", n => { SignaturesStatus = n.GetEnumValue<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_signaturesStatus>(); } },
                { "status", n => { Status = n.GetObjectValue<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_status>(global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_status.CreateFromDiscriminatorValue); } },
                { "templateType", n => { TemplateType = n.GetObjectValue<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_templateType>(global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_templateType.CreateFromDiscriminatorValue); } },
                { "templateVersionId", n => { TemplateVersionId = n.GetIntValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "trades", n => { Trades = n.GetCollectionOfObjectValues<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_trades>(global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_trades.CreateFromDiscriminatorValue)?.AsList(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "urn", n => { Urn = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("allowSectionAssignee", AllowSectionAssignee);
            writer.WriteCollectionOfObjectValues<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_assignees>("assignees", Assignees);
            writer.WriteDoubleValue("completedItemsCount", CompletedItemsCount);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteDateTimeOffsetValue("deletedAt", DeletedAt);
            writer.WriteStringValue("instanceRevision", InstanceRevision);
            writer.WriteStringValue("instructions", Instructions);
            writer.WriteGuidValue("location", Location);
            writer.WriteStringValue("modifiedBy", ModifiedBy);
            writer.WriteCollectionOfPrimitiveValues<string>("permittedActions", PermittedActions);
            writer.WriteCollectionOfPrimitiveValues<string>("permittedAttributes", PermittedAttributes);
            writer.WriteDoubleValue("progress", Progress);
            writer.WriteDateTimeOffsetValue("scheduledDate", ScheduledDate);
            writer.WriteCollectionOfObjectValues<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_signatures>("signatures", Signatures);
            writer.WriteEnumValue<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_signaturesStatus>("signaturesStatus", SignaturesStatus);
            writer.WriteObjectValue<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_status>("status", Status);
            writer.WriteObjectValue<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_templateType>("templateType", TemplateType);
            writer.WriteIntValue("templateVersionId", TemplateVersionId);
            writer.WriteStringValue("title", Title);
            writer.WriteCollectionOfObjectValues<global::Autodesk.BIM360.Bim360.Checklists.V1.Containers.Item.Instances.InstancesGetResponse_data_attributes_trades>("trades", Trades);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteStringValue("urn", Urn);
        }
    }
}
#pragma warning restore CS0618
