// <auto-generated/>
#pragma warning disable CS0618
using Autodesk.ACC.Bim360.Clash.V3.Containers.Item.Clashes.Assigned.Viewcontext;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Autodesk.ACC.Bim360.Clash.V3.Containers.Item.Clashes.Assigned
{
    /// <summary>
    /// Builds and executes requests for operations under \bim360\clash\v3\containers\{containerId}\clashes\assigned
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AssignedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The viewcontext property</summary>
        public global::Autodesk.ACC.Bim360.Clash.V3.Containers.Item.Clashes.Assigned.Viewcontext.ViewcontextRequestBuilder Viewcontext
        {
            get => new global::Autodesk.ACC.Bim360.Clash.V3.Containers.Item.Clashes.Assigned.Viewcontext.ViewcontextRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.Bim360.Clash.V3.Containers.Item.Clashes.Assigned.AssignedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssignedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bim360/clash/v3/containers/{containerId}/clashes/assigned", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.Bim360.Clash.V3.Containers.Item.Clashes.Assigned.AssignedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssignedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bim360/clash/v3/containers/{containerId}/clashes/assigned", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
