// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.DataManagement.OSS.Models
{
    /// <summary>
    /// Bucket Payload Body Structure
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Create_buckets_payload : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allow property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Autodesk.DataManagement.OSS.Models.Create_buckets_payload_allow>? Allow { get; set; }
#nullable restore
#else
        public List<global::Autodesk.DataManagement.OSS.Models.Create_buckets_payload_allow> Allow { get; set; }
#endif
        /// <summary>Bucket key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BucketKey { get; set; }
#nullable restore
#else
        public string BucketKey { get; set; }
#endif
        /// <summary>[Data retention policy](https://developer.autodesk.com/en/docs/data/v2/overview/retention-policy/)Acceptable values: `transient`, `temporary` or `persistent`</summary>
        public global::Autodesk.DataManagement.OSS.Models.Create_buckets_payload_policyKey? PolicyKey { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.DataManagement.OSS.Models.Create_buckets_payload"/> and sets the default values.
        /// </summary>
        public Create_buckets_payload()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.DataManagement.OSS.Models.Create_buckets_payload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.DataManagement.OSS.Models.Create_buckets_payload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.DataManagement.OSS.Models.Create_buckets_payload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allow", n => { Allow = n.GetCollectionOfObjectValues<global::Autodesk.DataManagement.OSS.Models.Create_buckets_payload_allow>(global::Autodesk.DataManagement.OSS.Models.Create_buckets_payload_allow.CreateFromDiscriminatorValue)?.AsList(); } },
                { "bucketKey", n => { BucketKey = n.GetStringValue(); } },
                { "policyKey", n => { PolicyKey = n.GetEnumValue<global::Autodesk.DataManagement.OSS.Models.Create_buckets_payload_policyKey>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Autodesk.DataManagement.OSS.Models.Create_buckets_payload_allow>("allow", Allow);
            writer.WriteStringValue("bucketKey", BucketKey);
            writer.WriteEnumValue<global::Autodesk.DataManagement.OSS.Models.Create_buckets_payload_policyKey>("policyKey", PolicyKey);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
