// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UsersGetResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Contains pagination details for the records returned by the endpoint.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users.UsersGetResponse_pagination? Pagination { get; set; }
#nullable restore
#else
        public global::Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users.UsersGetResponse_pagination Pagination { get; set; }
#endif
        /// <summary>The requested page of project users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users.UsersGetResponse_results>? Results { get; set; }
#nullable restore
#else
        public List<global::Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users.UsersGetResponse_results> Results { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users.UsersGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users.UsersGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users.UsersGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "pagination", n => { Pagination = n.GetObjectValue<global::Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users.UsersGetResponse_pagination>(global::Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users.UsersGetResponse_pagination.CreateFromDiscriminatorValue); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users.UsersGetResponse_results>(global::Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users.UsersGetResponse_results.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users.UsersGetResponse_pagination>("pagination", Pagination);
            writer.WriteCollectionOfObjectValues<global::Autodesk.BIM360.Construction.Admin.V1.Projects.Item.Users.UsersGetResponse_results>("results", Results);
        }
    }
}
#pragma warning restore CS0618
