// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.BIM360.Bim360.Clash.V3.Containers.Item.Tests.Item.ClashesClose
{
    /// <summary>The current job status. Possible values: ``Failed``, ``Running``, ``Succeeded``, ``Archived``.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ClashesClosePostResponse_status
    {
        [EnumMember(Value = "Failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "Running")]
        #pragma warning disable CS1591
        Running,
        #pragma warning restore CS1591
        [EnumMember(Value = "Succeeded")]
        #pragma warning disable CS1591
        Succeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "Archived")]
        #pragma warning disable CS1591
        Archived,
        #pragma warning restore CS1591
    }
}
