// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate
{
    /// <summary>
    /// Builds and executes requests for operations under \bim360\docs\v1\projects\{project-id}\versions\{version_id}\custom-attributes:batch-update
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomAttributesBatchUpdateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomAttributesBatchUpdateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bim360/docs/v1/projects/{project%2Did}/versions/{version_id}/custom-attributes:batch-update", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomAttributesBatchUpdateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bim360/docs/v1/projects/{project%2Did}/versions/{version_id}/custom-attributes:batch-update", rawUrl)
        {
        }
        /// <summary>
        /// Assigns values to custom attributes for multiple documents. This endpoint also clears custom attribute values.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdatePostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdatePostResponse?> PostAsCustomAttributesBatchUpdatePostResponseAsync(global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdatePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdatePostResponse> PostAsCustomAttributesBatchUpdatePostResponseAsync(global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdatePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdatePostResponse>(requestInfo, global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdatePostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Assigns values to custom attributes for multiple documents. This endpoint also clears custom attribute values.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdateResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsCustomAttributesBatchUpdatePostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdateResponse?> PostAsync(global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdatePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdateResponse> PostAsync(global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdatePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdateResponse>(requestInfo, global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdateResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Assigns values to custom attributes for multiple documents. This endpoint also clears custom attribute values.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdatePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdatePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdateRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdateRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Autodesk.ACC.Bim360.Docs.V1.Projects.Item.Versions.Item.CustomAttributesBatchUpdate.CustomAttributesBatchUpdateRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CustomAttributesBatchUpdateRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
