// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.Construction.Reviews.V1.Projects.Item.Reviews.Item
{
    /// <summary>The current status of the review.Possible values: ``OPEN``, ``CLOSED``, ``VOID``, ``FAILED``.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithReviewGetResponse_status
    {
        [EnumMember(Value = "OPEN")]
        #pragma warning disable CS1591
        OPEN,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLOSED")]
        #pragma warning disable CS1591
        CLOSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "VOID")]
        #pragma warning disable CS1591
        VOID,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        FAILED,
        #pragma warning restore CS1591
    }
}
