// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Rfis
{
    /// <summary>The status of the official response to the RFI.Possible values: ``unanswered``, ``answered``.Always ``unanswered`` when creating an RFI.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RfisPostResponse_officialResponseStatus
    {
        [EnumMember(Value = "unanswered")]
        #pragma warning disable CS1591
        Unanswered,
        #pragma warning restore CS1591
        [EnumMember(Value = "answered")]
        #pragma warning disable CS1591
        Answered,
        #pragma warning restore CS1591
    }
}
