// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.BuildingConnected.Construction.Buildingconnected.V2.Projects.Item.CostsBatchPatch
{
    /// <summary>The method by which the cost is calculated. Possible values:- `LUMP_SUM`- `PERCENTAGE`- `RATE`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CostsBatchPatchPatchRequestBody_Asterisk_calculationType
    {
        [EnumMember(Value = "LUMP_SUM")]
        #pragma warning disable CS1591
        LUMP_SUM,
        #pragma warning restore CS1591
        [EnumMember(Value = "PERCENTAGE")]
        #pragma warning disable CS1591
        PERCENTAGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "RATE")]
        #pragma warning disable CS1591
        RATE,
        #pragma warning restore CS1591
    }
}
