// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ImportPostResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The failure property</summary>
        public int? Failure { get; set; }
        /// <summary>The failure_items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import.ImportPostResponse_failure_items>? FailureItems { get; set; }
#nullable restore
#else
        public List<global::Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import.ImportPostResponse_failure_items> FailureItems { get; set; }
#endif
        /// <summary>The success property</summary>
        public int? Success { get; set; }
        /// <summary>The success_items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import.ImportPostResponse_success_items>? SuccessItems { get; set; }
#nullable restore
#else
        public List<global::Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import.ImportPostResponse_success_items> SuccessItems { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import.ImportPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import.ImportPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import.ImportPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "failure", n => { Failure = n.GetIntValue(); } },
                { "failure_items", n => { FailureItems = n.GetCollectionOfObjectValues<global::Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import.ImportPostResponse_failure_items>(global::Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import.ImportPostResponse_failure_items.CreateFromDiscriminatorValue)?.AsList(); } },
                { "success", n => { Success = n.GetIntValue(); } },
                { "success_items", n => { SuccessItems = n.GetCollectionOfObjectValues<global::Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import.ImportPostResponse_success_items>(global::Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import.ImportPostResponse_success_items.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("failure", Failure);
            writer.WriteCollectionOfObjectValues<global::Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import.ImportPostResponse_failure_items>("failure_items", FailureItems);
            writer.WriteIntValue("success", Success);
            writer.WriteCollectionOfObjectValues<global::Autodesk.BIM360.Hq.V1.Accounts.Item.Users.Import.ImportPostResponse_success_items>("success_items", SuccessItems);
        }
    }
}
#pragma warning restore CS0618
