// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.Metadata
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MetadataGetResponse_versions : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The date and time the version was created in ISO8601 format. For example, ``2023-01-17T09:54:27.000Z``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>``true`` if this is the current version``false`` if this is not the current version</summary>
        public bool? CurrentVersion { get; set; }
        /// <summary>The ID of the AutoSpecs version, generated by AutoSpecs when creating the new version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The version name provided by the user when creating the version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The status of the specification extraction. Note that Smart Register data (GET smartRegster) is only available when the status is ``Completed``.Note that we do not currently support webhooks for the AutoSpecs API.Possible values: ``Completed``, ``In Progress``, ``Failed``</summary>
        public global::Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.Metadata.MetadataGetResponse_versions_status? Status { get; set; }
        /// <summary>The last date and time the version was updated in in ISO8601. For example ``2023-01-17T09:54:27.000Z``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.Metadata.MetadataGetResponse_versions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.Metadata.MetadataGetResponse_versions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.Metadata.MetadataGetResponse_versions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetStringValue(); } },
                { "currentVersion", n => { CurrentVersion = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.Metadata.MetadataGetResponse_versions_status>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("createdAt", CreatedAt);
            writer.WriteBoolValue("currentVersion", CurrentVersion);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Autodesk.ACC.Construction.Autospecs.V1.Projects.Item.Metadata.MetadataGetResponse_versions_status>("status", Status);
            writer.WriteStringValue("updatedAt", UpdatedAt);
        }
    }
}
#pragma warning restore CS0618
