// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.BIM360.Cost.V1.Containers.Item.Workflows.Actions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ActionsPostRequestBody : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Name of the action to perform. The possible actions are from ``GET /actions``.Max length: 255</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Action { get; set; }
#nullable restore
#else
        public string Action { get; set; }
#endif
        /// <summary>The ID of the item on which to perform the action. For example, change order ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssociationId { get; set; }
#nullable restore
#else
        public string AssociationId { get; set; }
#endif
        /// <summary>The type of the item on which to perform the action. Possible values: ``FormInstance``, ``OCO``, ``PCO``, ``RCO``, ``RFQ``, ``SCO``, ``Expense``, ``Contract``, ``CostPayment``, ``BudgetPayment``, ``BudgetTransfer``, ``MainContract``, ``DistributionItem``.</summary>
        public global::Autodesk.BIM360.Cost.V1.Containers.Item.Workflows.Actions.ActionsPostRequestBody_associationType? AssociationType { get; set; }
        /// <summary>Extra data required by the action.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Autodesk.BIM360.Cost.V1.Containers.Item.Workflows.Actions.ActionsPostRequestBody_options? Options { get; set; }
#nullable restore
#else
        public global::Autodesk.BIM360.Cost.V1.Containers.Item.Workflows.Actions.ActionsPostRequestBody_options Options { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.BIM360.Cost.V1.Containers.Item.Workflows.Actions.ActionsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.BIM360.Cost.V1.Containers.Item.Workflows.Actions.ActionsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.BIM360.Cost.V1.Containers.Item.Workflows.Actions.ActionsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetStringValue(); } },
                { "associationId", n => { AssociationId = n.GetStringValue(); } },
                { "associationType", n => { AssociationType = n.GetEnumValue<global::Autodesk.BIM360.Cost.V1.Containers.Item.Workflows.Actions.ActionsPostRequestBody_associationType>(); } },
                { "options", n => { Options = n.GetObjectValue<global::Autodesk.BIM360.Cost.V1.Containers.Item.Workflows.Actions.ActionsPostRequestBody_options>(global::Autodesk.BIM360.Cost.V1.Containers.Item.Workflows.Actions.ActionsPostRequestBody_options.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action", Action);
            writer.WriteStringValue("associationId", AssociationId);
            writer.WriteEnumValue<global::Autodesk.BIM360.Cost.V1.Containers.Item.Workflows.Actions.ActionsPostRequestBody_associationType>("associationType", AssociationType);
            writer.WriteObjectValue<global::Autodesk.BIM360.Cost.V1.Containers.Item.Workflows.Actions.ActionsPostRequestBody_options>("options", Options);
        }
    }
}
#pragma warning restore CS0618
