// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.ACC.Construction.Rfis.V3.Projects.Item.Rfis.Item
{
    /// <summary>The type of assignee. Will always be ``user``.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithRfiPatchRequestBody_assignedTo_type
    {
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
    }
}
