// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.Automation.Da.UsEast.V3.Appbundles
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AppbundlesPostRequestBody : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>A module referenced by an Activity in order to perform specific functions. Typically this is a DLL or some other form of custom code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Appbundles { get; set; }
#nullable restore
#else
        public List<string> Appbundles { get; set; }
#endif
        /// <summary>The actual processing engine that runs the WorkItem job and processes the Activity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Engine { get; set; }
#nullable restore
#else
        public string Engine { get; set; }
#endif
        /// <summary>Name of AppBundle, see the example section. Only alphanumeric characters and _ (underscore) are allowed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The URL that points to the zip package for the AppBundle or Engine.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Package { get; set; }
#nullable restore
#else
        public string Package { get; set; }
#endif
        /// <summary>The url/string Settings for a given set of AppBundles.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Autodesk.Automation.Da.UsEast.V3.Appbundles.AppbundlesPostRequestBody_settings? Settings { get; set; }
#nullable restore
#else
        public global::Autodesk.Automation.Da.UsEast.V3.Appbundles.AppbundlesPostRequestBody_settings Settings { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.Automation.Da.UsEast.V3.Appbundles.AppbundlesPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.Automation.Da.UsEast.V3.Appbundles.AppbundlesPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.Automation.Da.UsEast.V3.Appbundles.AppbundlesPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "appbundles", n => { Appbundles = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "engine", n => { Engine = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "package", n => { Package = n.GetStringValue(); } },
                { "settings", n => { Settings = n.GetObjectValue<global::Autodesk.Automation.Da.UsEast.V3.Appbundles.AppbundlesPostRequestBody_settings>(global::Autodesk.Automation.Da.UsEast.V3.Appbundles.AppbundlesPostRequestBody_settings.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("appbundles", Appbundles);
            writer.WriteStringValue("engine", Engine);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("package", Package);
            writer.WriteObjectValue<global::Autodesk.Automation.Da.UsEast.V3.Appbundles.AppbundlesPostRequestBody_settings>("settings", Settings);
        }
    }
}
#pragma warning restore CS0618
