// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.ACC.Cost.V1.Containers.Item.CostItems.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithCostItemGetResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The amount approved by the owner.</summary>
        public double? Approved { get; set; }
        /// <summary>The ID of the budget to which the cost item is linked.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BudgetId { get; set; }
#nullable restore
#else
        public string BudgetId { get; set; }
#endif
        /// <summary>The current budget status of the cost item, indicating its lifecycle stage.Possible values: ``draft``, ``open``, ``submitted``, ``accepted``, ``approved``, ``executed``, ``revising``, ``rejected``, ``void``.Note that you can only change the status by updating the associated change order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BudgetStatus { get; set; }
#nullable restore
#else
        public string BudgetStatus { get; set; }
#endif
        /// <summary>Not relevant</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BudgetTransferId { get; set; }
#nullable restore
#else
        public string BudgetTransferId { get; set; }
#endif
        /// <summary>Not relevant</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BudgetTransferItemId { get; set; }
#nullable restore
#else
        public string BudgetTransferItemId { get; set; }
#endif
        /// <summary>The amount committed to the supplier.</summary>
        public double? Committed { get; set; }
        /// <summary>The exchange rate used for the ``committed`` cost. If multi-currency was not enabled, the value is set to ``1`` regardless of the specified rate. Default value: ``1``.</summary>
        public double? CommittedExchangeRate { get; set; }
        /// <summary>The ID of the contract to which the cost item is linked.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContractId { get; set; }
#nullable restore
#else
        public string ContractId { get; set; }
#endif
        /// <summary>The current financial approval status of the cost item.Possible values: ``draft``, ``open``, ``revising``, ``pricing``, ``proposed``, ``approved``, ``executed``, ``rejected``, ``contracted``, ``accepted``, ``void``.Note that the cost status can only be changed by updating the associated change order.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CostStatus { get; set; }
#nullable restore
#else
        public string CostStatus { get; set; }
#endif
        /// <summary>The date and time that the item was created, in ISO 8601 format.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>A detailed description of the cost item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The rough estimate of the cost item without a formal quote.</summary>
        public double? Estimated { get; set; }
        /// <summary>The identifier assigned to an item in its original external ERP system. Use this ID to track and look up data within the integrated system. Note that this value comes from the item&apos;s ID in the external system.Max length: 255</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>A message generated by the external ERP system that explains the sync status of the integration. For example, common values include ``success`` or ``fail`` to indicate the result of the integration operation.Max length: 255</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalMessage { get; set; }
#nullable restore
#else
        public string ExternalMessage { get; set; }
#endif
        /// <summary>The name of the external ERP system integrated with Cost Management. Use this name to identify and search for data within the integrated system.Max length: 255</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalSystem { get; set; }
#nullable restore
#else
        public string ExternalSystem { get; set; }
#endif
        /// <summary>The unique identifier of the cost item.</summary>
        public Guid? Id { get; set; }
        /// <summary>The initial quantity of the proposed cost item as specified in the budget or contract.</summary>
        public double? InputQuantity { get; set; }
        /// <summary>The state of the item during the integration with the external ERP system (such as SignNow). An item can be a ``budget``, ``contract``, ``main contract``, ``main contract item``, ``cost item``, ``expense``, ``expense item``, ``change order``, or ``schedule of value``. For more details, see `Integrate with External System &lt;/en/docs/acc/v1/tutorials/cost/integrate-with-external-system/&gt;`_ tutorial.Possible values:``locked``: the item is currently locked within the ERP system, preventing modifications until unlocked. To unlock and modify the item, use the relevant PATCH endpoint to set ``integrationState`` to ``null``. For example, for a budget, call `PATCH budgets &lt;en/docs/bim360/v1/reference/http/cost-budgets-budgetId-PATCH/&gt;`_. For a contract, call `PATCH contracts &lt;en/docs/bim360/v1/reference/http/cost-contracts-contractId-PATCH/&gt;`_. For more details, see the `Help documentation &lt;https://help.autodesk.com/view/BUILD/ENU/?guid=Integrated_and_Locked&gt;`_.``integrated``: the item has been successfully added to the ERP system.``failed``: the item encountered an error during the integration process and was not successfully added to the ERP system. For example, if a user tries to integrate ``contracts`` from an ERP system and the updates fail, the ``integrationState`` can be set to ``failed``. Retry the sync process or analyze the issue if it continues to fail.``null``: The item has not been integrated with the ERP system. This is default value.For more information regarding integrations within the Cost Management system, see `Integrations in Cost Management &lt;https://help.autodesk.com/view/BUILD/ENU/?guid=Cost_Integrations&gt;`_.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IntegrationState { get; set; }
#nullable restore
#else
        public string IntegrationState { get; set; }
#endif
        /// <summary>The date and time that the item&apos;s integration status was last changed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IntegrationStateChangedAt { get; set; }
#nullable restore
#else
        public string IntegrationStateChangedAt { get; set; }
#endif
        /// <summary>The user who last changed the integration status. This is the ID of a user managed by the BIM 360/ACC Admin.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IntegrationStateChangedBy { get; set; }
#nullable restore
#else
        public string IntegrationStateChangedBy { get; set; }
#endif
        /// <summary>Indicates if the cost item includes a markup.``true``: the item is a markup cost item.``false``: (default) the item is not a markup cost item.</summary>
        public bool? IsMarkup { get; set; }
        /// <summary>The date and time when the item was last synchronized with the external ERP system. This value is updated by the external system and is in ISO 8601 format.</summary>
        public DateTimeOffset? LastSyncTime { get; set; }
        /// <summary>A list of the IDs of the project locations where this item applies, along with the node paths of these locations in the project&apos;s locations tree.For more information, see the Locations `Help documentation &lt;https://aps.autodesk.com/en/docs/bim360/v1/reference/http/locations-nodes-GET/&gt;`_ help.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? LocationPaths { get; set; }
#nullable restore
#else
        public List<string> LocationPaths { get; set; }
#endif
        /// <summary>A list of the IDs of the project locations where this item applies.For more information, see the Locations `Help documentation &lt;https://aps.autodesk.com/en/docs/bim360/v1/reference/http/locations-nodes-GET/&gt;`_ help.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Locations { get; set; }
#nullable restore
#else
        public List<string> Locations { get; set; }
#endif
        /// <summary>The name of the cost item.Max length: 255</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>A note associated with the cost item, formatted as Tiptap rich text (https://tiptap.dev/introduction/).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>The system generated sequential number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>The quoted cost of the cost item provided by the supplier.</summary>
        public double? Proposed { get; set; }
        /// <summary>The exchange rate used for the ``proposed`` cost. If multi-currency was not enabled, the value is set to ``1`` regardless of the specified rate. Default value: ``1``.</summary>
        public double? ProposedExchangeRate { get; set; }
        /// <summary>The total quantity of the cost item.</summary>
        public double? Quantity { get; set; }
        /// <summary>Defines the project&apos;s scope status of the cost item. Possible values: ``out``, ``in``, ``tbd``, ``budgetOnly``, ``contingency``.</summary>
        public global::Autodesk.ACC.Cost.V1.Containers.Item.CostItems.Item.WithCostItemGetResponse_scope? Scope { get; set; }
        /// <summary>The scope of work of the cost items, formatted as Tiptap rich text (https://tiptap.dev/introduction/).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScopeOfWork { get; set; }
#nullable restore
#else
        public string ScopeOfWork { get; set; }
#endif
        /// <summary>Not relevant</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Autodesk.ACC.Cost.V1.Containers.Item.CostItems.Item.WithCostItemGetResponse_splitNumber? SplitNumber { get; set; }
#nullable restore
#else
        public global::Autodesk.ACC.Cost.V1.Containers.Item.CostItems.Item.WithCostItemGetResponse_splitNumber SplitNumber { get; set; }
#endif
        /// <summary>The amount submitted to the owner for approval.</summary>
        public double? Submitted { get; set; }
        /// <summary>The category or classification of the cost item, which the Project Admin can customize.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The unit of measurement for the cost item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Unit { get; set; }
#nullable restore
#else
        public string Unit { get; set; }
#endif
        /// <summary>The date and time that the item was last updated, in ISO 8601 format.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.ACC.Cost.V1.Containers.Item.CostItems.Item.WithCostItemGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.ACC.Cost.V1.Containers.Item.CostItems.Item.WithCostItemGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.ACC.Cost.V1.Containers.Item.CostItems.Item.WithCostItemGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approved", n => { Approved = n.GetDoubleValue(); } },
                { "budgetId", n => { BudgetId = n.GetStringValue(); } },
                { "budgetStatus", n => { BudgetStatus = n.GetStringValue(); } },
                { "budgetTransferId", n => { BudgetTransferId = n.GetStringValue(); } },
                { "budgetTransferItemId", n => { BudgetTransferItemId = n.GetStringValue(); } },
                { "committed", n => { Committed = n.GetDoubleValue(); } },
                { "committedExchangeRate", n => { CommittedExchangeRate = n.GetDoubleValue(); } },
                { "contractId", n => { ContractId = n.GetStringValue(); } },
                { "costStatus", n => { CostStatus = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "estimated", n => { Estimated = n.GetDoubleValue(); } },
                { "externalId", n => { ExternalId = n.GetStringValue(); } },
                { "externalMessage", n => { ExternalMessage = n.GetStringValue(); } },
                { "externalSystem", n => { ExternalSystem = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "inputQuantity", n => { InputQuantity = n.GetDoubleValue(); } },
                { "integrationState", n => { IntegrationState = n.GetStringValue(); } },
                { "integrationStateChangedAt", n => { IntegrationStateChangedAt = n.GetStringValue(); } },
                { "integrationStateChangedBy", n => { IntegrationStateChangedBy = n.GetStringValue(); } },
                { "isMarkup", n => { IsMarkup = n.GetBoolValue(); } },
                { "lastSyncTime", n => { LastSyncTime = n.GetDateTimeOffsetValue(); } },
                { "locationPaths", n => { LocationPaths = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "locations", n => { Locations = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "proposed", n => { Proposed = n.GetDoubleValue(); } },
                { "proposedExchangeRate", n => { ProposedExchangeRate = n.GetDoubleValue(); } },
                { "quantity", n => { Quantity = n.GetDoubleValue(); } },
                { "scope", n => { Scope = n.GetEnumValue<global::Autodesk.ACC.Cost.V1.Containers.Item.CostItems.Item.WithCostItemGetResponse_scope>(); } },
                { "scopeOfWork", n => { ScopeOfWork = n.GetStringValue(); } },
                { "splitNumber", n => { SplitNumber = n.GetObjectValue<global::Autodesk.ACC.Cost.V1.Containers.Item.CostItems.Item.WithCostItemGetResponse_splitNumber>(global::Autodesk.ACC.Cost.V1.Containers.Item.CostItems.Item.WithCostItemGetResponse_splitNumber.CreateFromDiscriminatorValue); } },
                { "submitted", n => { Submitted = n.GetDoubleValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "unit", n => { Unit = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("approved", Approved);
            writer.WriteStringValue("budgetId", BudgetId);
            writer.WriteStringValue("budgetStatus", BudgetStatus);
            writer.WriteStringValue("budgetTransferId", BudgetTransferId);
            writer.WriteStringValue("budgetTransferItemId", BudgetTransferItemId);
            writer.WriteDoubleValue("committed", Committed);
            writer.WriteDoubleValue("committedExchangeRate", CommittedExchangeRate);
            writer.WriteStringValue("contractId", ContractId);
            writer.WriteStringValue("costStatus", CostStatus);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteDoubleValue("estimated", Estimated);
            writer.WriteStringValue("externalId", ExternalId);
            writer.WriteStringValue("externalMessage", ExternalMessage);
            writer.WriteStringValue("externalSystem", ExternalSystem);
            writer.WriteGuidValue("id", Id);
            writer.WriteDoubleValue("inputQuantity", InputQuantity);
            writer.WriteStringValue("integrationState", IntegrationState);
            writer.WriteStringValue("integrationStateChangedAt", IntegrationStateChangedAt);
            writer.WriteStringValue("integrationStateChangedBy", IntegrationStateChangedBy);
            writer.WriteBoolValue("isMarkup", IsMarkup);
            writer.WriteDateTimeOffsetValue("lastSyncTime", LastSyncTime);
            writer.WriteCollectionOfPrimitiveValues<string>("locationPaths", LocationPaths);
            writer.WriteCollectionOfPrimitiveValues<string>("locations", Locations);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("note", Note);
            writer.WriteStringValue("number", Number);
            writer.WriteDoubleValue("proposed", Proposed);
            writer.WriteDoubleValue("proposedExchangeRate", ProposedExchangeRate);
            writer.WriteDoubleValue("quantity", Quantity);
            writer.WriteEnumValue<global::Autodesk.ACC.Cost.V1.Containers.Item.CostItems.Item.WithCostItemGetResponse_scope>("scope", Scope);
            writer.WriteStringValue("scopeOfWork", ScopeOfWork);
            writer.WriteObjectValue<global::Autodesk.ACC.Cost.V1.Containers.Item.CostItems.Item.WithCostItemGetResponse_splitNumber>("splitNumber", SplitNumber);
            writer.WriteDoubleValue("submitted", Submitted);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("unit", Unit);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
        }
    }
}
#pragma warning restore CS0618
