// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.BuildingConnected.Construction.Buildingconnected.V2.Projects.Item
{
    /// <summary>Indicates whether the project was won or lost. Defaults to `UNKNOWN` until changed. Possible values:- `WON`- `LOST`- `UNKNOWN` (Default)Note that this value is private to your company and not displayed to bidders.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithProjectPatchResponse_awarded
    {
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        UNKNOWN,
        #pragma warning restore CS1591
        [EnumMember(Value = "WON")]
        #pragma warning disable CS1591
        WON,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOST")]
        #pragma warning disable CS1591
        LOST,
        #pragma warning restore CS1591
    }
}
