// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item
{
    /// <summary>Defines this output definition to be of PDF type Will always be: `PDF`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithReleasePatchResponse_outputSettings_anyOf_Zero_oneOf_InventorPDFOutput_type
    {
        [EnumMember(Value = "PDF")]
        #pragma warning disable CS1591
        PDF,
        #pragma warning restore CS1591
    }
}
