// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithReleasePatchRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Release notes for this Dynamic Content Definition.Max length: 500</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The list of Output settings for this Release.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody_outputSettings? OutputSettings { get; set; }
#nullable restore
#else
        public global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody_outputSettings OutputSettings { get; set; }
#endif
        /// <summary>The Release state.Possible values: `ACTIVE`, `INACTIVE`, `OBSOLETE`</summary>
        public global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody_state? State { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody"/> and sets the default values.
        /// </summary>
        public WithReleasePatchRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "outputSettings", n => { OutputSettings = n.GetObjectValue<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody_outputSettings>(global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody_outputSettings.CreateFromDiscriminatorValue); } },
                { "state", n => { State = n.GetEnumValue<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody_state>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("notes", Notes);
            writer.WriteObjectValue<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody_outputSettings>("outputSettings", OutputSettings);
            writer.WriteEnumValue<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody_state>("state", State);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
