// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \industrialized-construction\informed-design\v1\releases\{releaseId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithReleaseItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithReleaseItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/industrialized-construction/informed-design/v1/releases/{releaseId}?accessId={accessId}&accessType={accessType}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithReleaseItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/industrialized-construction/informed-design/v1/releases/{releaseId}?accessId={accessId}&accessType={accessType}", rawUrl)
        {
        }
        /// <summary>
        /// Deletes a Release of a Product, and any Variants or Outputs for that Release. The Release is specified by the client provided `releaseId` URI parameter.
        /// Online documentation <see href="https://aps.autodesk.com/en/docs/informed-design/v1/reference/quick_reference/informed-design-api-deleterelease-DELETE" />
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder.WithReleaseItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder.WithReleaseItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the details of a Release. The Release is specified by the client provided `releaseId` URI parameter.
        /// Online documentation <see href="https://aps.autodesk.com/en/docs/informed-design/v1/reference/quick_reference/informed-design-api-getrelease-GET" />
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseGetResponse?> GetAsync(Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder.WithReleaseItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseGetResponse> GetAsync(Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder.WithReleaseItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseGetResponse>(requestInfo, global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates Release of a Product. The Release is specified by the client provided `releaseId` URI parameter.
        /// Online documentation <see href="https://aps.autodesk.com/en/docs/informed-design/v1/reference/quick_reference/informed-design-api-patchrelease-PATCH" />
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchResponse?> PatchAsync(global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody body, Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder.WithReleaseItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchResponse> PatchAsync(global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody body, Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder.WithReleaseItemRequestBuilderPatchQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchResponse>(requestInfo, global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Deletes a Release of a Product, and any Variants or Outputs for that Release. The Release is specified by the client provided `releaseId` URI parameter.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder.WithReleaseItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder.WithReleaseItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns the details of a Release. The Release is specified by the client provided `releaseId` URI parameter.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder.WithReleaseItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder.WithReleaseItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Updates Release of a Product. The Release is specified by the client provided `releaseId` URI parameter.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody body, Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder.WithReleaseItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleasePatchRequestBody body, Action<RequestConfiguration<global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder.WithReleaseItemRequestBuilderPatchQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.WithReleaseItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Deletes a Release of a Product, and any Variants or Outputs for that Release. The Release is specified by the client provided `releaseId` URI parameter.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithReleaseItemRequestBuilderDeleteQueryParameters 
        {
            /// <summary>A composite string of identifiers that define the access scope for the given access type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("accessId")]
            public string? AccessId { get; set; }
#nullable restore
#else
            [QueryParameter("accessId")]
            public string AccessId { get; set; }
#endif
            /// <summary>The type of integration or service used to determine access context.Possible values: `ACC`, `BIM360`, `FUSION`, `CONTENTCATALOG`</summary>
            [QueryParameter("accessType")]
            public global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.DeleteAccessTypeQueryParameterType? AccessType { get; set; }
        }
        /// <summary>
        /// Returns the details of a Release. The Release is specified by the client provided `releaseId` URI parameter.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithReleaseItemRequestBuilderGetQueryParameters 
        {
            /// <summary>A composite string of identifiers that define the access scope for the given access type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("accessId")]
            public string? AccessId { get; set; }
#nullable restore
#else
            [QueryParameter("accessId")]
            public string AccessId { get; set; }
#endif
            /// <summary>The type of integration or service used to determine access context.Possible values: `ACC`, `BIM360`, `FUSION`, `CONTENTCATALOG`, `BRIDGE`, `PUBLIC`</summary>
            [QueryParameter("accessType")]
            public global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.GetAccessTypeQueryParameterType? AccessType { get; set; }
        }
        /// <summary>
        /// Updates Release of a Product. The Release is specified by the client provided `releaseId` URI parameter.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithReleaseItemRequestBuilderPatchQueryParameters 
        {
            /// <summary>A composite string of identifiers that define the access scope for the given access type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("accessId")]
            public string? AccessId { get; set; }
#nullable restore
#else
            [QueryParameter("accessId")]
            public string AccessId { get; set; }
#endif
            /// <summary>The type of integration or service used to determine access context.Possible values: `ACC`, `BIM360`, `FUSION`, `CONTENTCATALOG`</summary>
            [QueryParameter("accessType")]
            public global::Autodesk.InformedDesign.IndustrializedConstruction.InformedDesign.V1.Releases.Item.PatchAccessTypeQueryParameterType? AccessType { get; set; }
        }
    }
}
#pragma warning restore CS0618
